name: Reusable Python C interface unit tests

on:
  workflow_call:
    inputs:
      additional-apt-packages:
        description: 'Additional APT packages to install'
        required: false
        type: string
        default: ''
      pyproject-directory:
        description: 'Directory to find pyproject.toml'
        required: false
        type: string
        default: '.'
      tests:
        description: 'Low-level tests to run'
        required: false
        type: string
        default: 'tests/test_python_c.py'

permissions:
  contents: read

jobs:
  python-c-tests:
    name: Python-C unit tests
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66  # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          submodules: true
          persist-credentials: false

      - name: Install dev tools
        if: ${{ inputs.additional-apt-packages != '' }}
        env:
          ADDITIONAL_APT_PACKAGES: ${{ inputs.additional-apt-packages }}
        run: |
          sudo apt-get update && sudo apt-get install -y ${ADDITIONAL_APT_PACKAGES}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          version: "0.10.0"

      - name: Install Python dependencies
        env:
          PYPROJECT_DIRECTORY: ${{ inputs.pyproject-directory }}
        run: uv sync  --project=${PYPROJECT_DIRECTORY} --locked --group test --no-default-groups

      - name: Install gcovr
        run: uv tool install gcovr==8.6

      - name: Build module
        working-directory: ${{ inputs.pyproject-directory }}
        run: CFLAGS=--coverage uv run --no-default-groups python setup.py build_ext --inplace

      - name: Run low-level tests
        env:
          PYPROJECT_DIRECTORY: ${{ inputs.pyproject-directory }}
          TESTS: ${{ inputs.tests }}
        run: |
          uv run --project=${PYPROJECT_DIRECTORY} --locked --group test --no-default-groups \
            pytest ${TESTS}

      - name: Run gcovr
        run: uv tool run gcovr --clover coverage.xml --txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          disable_search: true
          verbose: true
          flags: c-python
          fail_ci_if_error: true
